# escape=`
FROM plugins/base:windows-1809-amd64

LABEL maintainer=""Joel Damata <joel.damata94@gmail.com>"" `
  org.label-schema.name="" `
  org.label-schema.vendor="Drone.IO Community" `
  org.label-schema.schema-version="1.0"

ADD release/windows/amd64/drone-teams.exe C:/bin/drone-teams.exe
ENTRYPOINT [ "C:\\bin\\drone-teams.exe" ]
