FROM plugins/base:linux-arm64

LABEL maintainer="Joel Damata <joel.damata94@gmail.com>" \
  org.label-schema.vendor="Drone.IO Community" \
  org.label-schema.schema-version="1.0"

ADD release/linux/arm64/drone-teams /bin/
ENTRYPOINT [ "/bin/drone-teams" ]
